runtime: custom
env: flex
resources:
  cpu: 1
  memory_gb: 0.6
automatic_scaling:
  min_num_instances: 1
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300
