version: 0.1

phases:
  build:
    commands:
      - echo Packaging started on `date` ...
      - sbt codePipeline
      - echo Packaging completed on `date`
artifacts:
  files:
    - Dockerfile
    - opt/**/*
eb_codebuild_settings:
  CodeBuildServiceRole: codebuild-docka-build-service-role
  ComputeType: BUILD_GENERAL1_SMALL
  Image: hseeberger/scala-sbt
  Timeout: 60
