version: 0.1

phases:
  build:
    commands:
      - echo Packaging started on `date` ...
      - sbt codePipeline
      - echo Packaging completed on `date`
artifacts:
  files:
    - Dockerfile
    - opt/**/*
