version: 0.1

phases:
  build:
    commands:
      - echo Packaging started on `date` ...
      - sbt docker:stage
      - echo Packaging completed on `date`
artifacts:
  files:
    - target/docker/stage/**/*
